### ISSUE TITLE
View POI Card faded pill portion color change

### ISSUE THREAD

**Issue by KatyaFoam** [f-o-a-m/foam.css#15]
I don't think, that the pill portion when not unfolded should be faded color. It looks to me like an unnecessary complexity. I would like these cards to have at least a little bit of the full (not faded) color to make them look sharper.

![Screen Shot 2018-06-08 at 1.24.15 PM.png](https://images.zenhubusercontent.com/59fb89d38a75884b9085d9c2/9a68dc16-b300-4d97-9406-f2a5f4b2bf84)

**Comment by safareli** [comment]
fixed in #16
